packages:
  - packages/*

catalogs:
  build:
    typescript: ^5.8.3
    vite: ^6.3.5
  format:
    '@ianvs/prettier-plugin-sort-imports': ^4.4.2
    prettier-plugin-packagejson: ^2.5.15
    prettier: ^3.5.3
  lint:
    '@eslint/js': ^9.28.0
    '@eslint/eslintrc': ^3.3.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react: ^7.37.5
    eslint: ^9.28.0
    typescript-eslint: ^8.33.1
    jiti: ^2.4.2
  test:
    vitest: ^3.2.2
    '@vitest/browser': ^3.2.2
    '@playwright/test': ^1.52.0
  types:
    '@types/node': ^22.15.30
  script:
    taze: ^19.1.0

ignoredBuiltDependencies:
  - esbuild
