packages:
  - packages/*
  - examples/*

catalogs:
  frontend:
    'react': '^19.1.0'
    'react-dom': '^19.1.0'
    'emittery': '^1.1.0'
  build:
    typescript: ^5.8.3
    vite: ^6.3.5
    sass: ^1.89.2
    tsdown: '^0.12.7'
    '@vitejs/plugin-react': '^4.5.2'
  format:
    '@ianvs/prettier-plugin-sort-imports': ^4.4.2
    prettier-plugin-packagejson: ^2.5.15
    prettier: ^3.5.3
  lint:
    '@eslint/js': ^9.29.0
    '@eslint/eslintrc': ^3.3.1
    eslint-plugin-react-hooks: ^5.2.0
    eslint-plugin-react: ^7.37.5
    eslint: ^9.29.0
    typescript-eslint: ^8.34.0
    jiti: ^2.4.2
  test:
    vitest: ^3.2.3
  types:
    '@types/node': ^22.15.31
    '@types/react': '^19.1.8'
    '@types/react-dom': '^19.1.6'
  script:
    taze: ^19.1.0
    'vite-node': '^3.2.3'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
